# https://dev.azure.com/lburais

trigger:
    branches:
      include:
      - master
    paths:
      include:
      - syncthing/*
  pr: none
  
  variables:
    - name: versionBuilder
      value: '2.0'
    - group: docker
  
  
  jobs:
  - template: /.azure/azp-template-addon.yml
    parameters:
      addon: 'syncthing'
      arch: '--all'